name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    - run: go version

    - run: sudo apt-get -y install libgpgme-dev libbtrfs-dev libdevmapper-dev
    - run: go run .
    - run: docker images
    - run: docker run docker.io/myusername/my-image
    